// File automatically generated by js17i18n. Don't modify.

const i18nData = { // eslint-disable-line
  "en": {
    "Accept": "Accept",
    "Keep connected": "Keep connected",
    "Login": "Login",
    "Password": "Password",
    "User": "User"
  },
  "es": {
    "Accept": "Aceptar",
    "Keep connected": "Mantenerse conectado",
    "Login": "Identificación",
    "Password": "Contraseña",
    "User": "Usuario"
  }
};