#!/bin/bash

SOURCES="src/*.js ../src/*.js"

# DON'T CHANGE vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

COMPILER=/deme/dmjs17/tools/closure-compiler-v20170806.jar
PRETTY=""
if [ "$1" == "pretty" ]
then
  PRETTY=" --compilation_level WHITESPACE_ONLY --formatting PRETTY_PRINT "
fi
SS=""
for SOURCE in $SOURCES
do
  SS=$SS" --js "$SOURCE
done

compile () {
  java -jar $COMPILER \
    --warning_level VERBOSE \
    --dependency_mode=STRICT \
    $SS \
    --entry_point Main \
    --js_output_file www/index.js \
    $PRETTY
}

echo "Compiling..."
compile
echo "... end compilation."
